development:
  database: blog_emberjs_development
  adapter: mysql2
  username: root
  password: 
  host: 127.0.0.1
  encoding: utf8

test:
  database: blog_emberjs_test
  adapter: mysql2
  username: root
  password: 
  host: 127.0.0.1
  encoding: utf8

production:
  database: blog_emberjs_production
  adapter: mysql2
  username: root
  password: 
  host: 127.0.0.1
  encoding: utf8
